### PR TITLE
Includes new golang IT into pipeline

### PR DESCRIPTION
**Pull request by himanshu-kun**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

**Review by AxiomSamarth — COMMENTED** [review]
Everything looks good to me. I believe, you are still working on the sanity of the code by cleaning up the unwanted commented lines. 

One question - why are there two files `pipeline_integration_test` and `pipeline_integration_test_copy`?

**Comment by himanshu-kun** [comment]
> Everything looks good to me. I believe, you are still working on the sanity of the code by cleaning up the unwanted commented lines.
> 
> One question - why are there two files `pipeline_integration_test` and `pipeline_integration_test_copy`?

sorry , I forgot to remove the cpy file. will change that

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

**Review by himanshu-kun — COMMENTED** [review]
Thanks for the PR. Just some minor changes requested. Also can you check the `make test-unit` and `make test-integration` once to see they are working fine

**Pull request merged**
