### PR TITLE
[rel-v0.9] Automated cherry pick of #65: Use proper version of klog

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area/dev-productivity
/area/ops-productivity
/kind/bug

Cherry pick of #65 on rel-v0.9.

#65: Use proper version of klog

**Release Notes:**
```bugfix operator
An issue causing klog's `--v` flag to be not respected is now fixed.
```

### CODE REVIEW

**Review by kon-angelo — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@himanshu-kun , the `test` step failed with:
```
  Unexpected error:
      <*awserr.requestError | 0xc011a0f700>: {
          awsError: <*awserr.baseError | 0xc011a0f6c0>{
              code: "AuthFailure",
              message: "AWS was not able to validate the provided access credentials",
              errs: nil,
          },
          statusCode: 401,
          requestID: "<omitted>",
          bytes: nil,
      }
```

I don't think this is related to the current PR. Can you help fixing the root cause for this issue?

**Review by himanshu-kun — APPROVED** [review]
/lgtm
The job is running now. It was again because of secret rotation.

**Comment by ialidzhikov** [comment]
> @ialidzhikov I have a bugfix in MCM as well, which needs to be hotfixed as well. So could you wait before you make the extension-aws hotfix release.

Sure, of course. Thanks for letting me know.

**Pull request merged**
